### ISSUE TITLE
Request for more information on permissions granted to extension

### ISSUE THREAD

**Issue by mpsulli** [bencooper222/firefox-address-bar-expression-parser#1]
Hi Ben, Thanks for creating this extension. I appreciate the improved accuracy over other options for solving math equations quickly in Firefox search bar. I'm wondering if you could update the extension description to explain what permissions are granted to this extension when enabled. Perhaps I'm missing something but I kept looking for something mentioning what data the extension would have access to (e.g. does it only have access to what's typed after "m@" or does it have access to all browsing URLs?)

**Comment by bencooper222** [comment]
Good idea. I'll try to get to this over the weekend.

**Comment by bencooper222** [comment]
Added to extension page
